version: '3.4'

x-template: &flyway-template
  image: flyway/flyway:latest
  volumes:
    - ./conf:/flyway/conf
    - ./drivers:/flyway/drivers
    - ./sql:/flyway/sql
  depends_on:
    - db

x-environment: &environment
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=db

services:
  clean:
    <<: *flyway-template
    command: clean

  migrate:
    <<: *flyway-template
    command: migrate

  info:
    <<: *flyway-template
    command: info

  db:
    image: postgres:latest
    environment: *environment
    ports:
      - 5432:5432
    container_name: db
